apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    component.opendatahub.io/name: jupyterhub
    opendatahub.io/component: "true"
  name: jupyterhub-img
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations:
      openshift.io/imported-from: quay.io/odh-jupyterhub/jupyterhub-img
    from:
      kind: DockerImage
      name: quay.io/vpavlin/jupyterhub-odh:mount-cm
    name: latest
    referencePolicy:
      type: Source
