---
apiVersion: v1
kind: Namespace
metadata:
  name: opendatahub
  labels:
    project: mlprague
spec:
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeflow
  labels:
    project: mlprague
spec:
